### ISSUE TITLE
"OpenGL texture binding not supported"

### ISSUE THREAD

**Issue by OtherAesop** [SergiusIW/chirperjax#2]
On a Windows machine (specific OS and hardware seems to be irrelevant) this project will not compile firstly due some missing lib files from the rust library which I documented a workaround for [here](https://github.com/SergiusIW/gate/issues/2) . After this issue is fixed, the project will run on a Linux machine but on a Windows platform when it attempts to bind textures it will panic with the error message mentioned in the title.

The panic occurs as a result of a call to sys::render::SDL::_GL_BindTexture(... , ...) on line 1500 of render.rs. I'm currently working on figuring out exactly what the error is. Based on some snooping though it appears that this function is known to be problematic and is likely a Windows only error.

Inside of gate this exception is thrown in gate/src/core/sdl/mod.rs at line 117 on the call to the function. I think the Linux implementation might just ignore the error message which could explain why this only works on Linux.

**Comment by MushuYoWushu** [comment]
Just an update, the only way I have found to bypass this bug is to set this up specifically on Debian. I tried 9.5 but something else could work

**Comment by joshuabenuck** [comment]
I found a fix for this issue. You need to set an SDL hint to set the renderer to `opengles2`. To manually patch Chirperjax, you can apply the changes from this [gist]( https://gist.github.com/joshuabenuck/87bf7358c274f3abba99d066d3a36dfe/revisions). Note: You may need to add `sdl2 = "*"` to your `Cargo.toml`.

The fix for gate itself is in [gate PR #6](https://github.com/SergiusIW/gate/pull/6). That will eliminate the need to apply this manual workaround.

**Comment by SergiusIW** [comment]
Chirperjax now depends on the latest gate version, which contains the fix mentioned above.
